### ISSUE TITLE
infinte loop when running on some CMS simulated events

### ISSUE THREAD

**Issue by govoni** [bvormwald/HHKinFit#1]
To whom it may concern, I am starting using this tool for a CMS analysis and when running on some MC samples I ended up in an infinite loop, due to this condition:

https://github.com/bvormwald/HHKinFit/blob/master/src/HHKinFit.cpp#L519

that was never satisfied.
It turns out that doubling the precision required, the loop nicely exits and I can run all my samples smoothly.

Would you advice making such a change in the code?

Best regards

**Comment by bvormwald** [comment]
Hi! Which kind of events are you fitting? The while-loop you are referring to just ensures that the tau mass is reached in the fit (in an iterative way). What exactly do you mean by "doubling the precision"?

Best regards, Benedikt

**Comment by govoni** [comment]
Hello Benedikt, thanks for the quick reply.

It's a DY event, spring 15, 25ns.
By doubling the precision, I mean changing 0.000001 into 0.000002, since I checked that for that special event only (out of many millions) the fabs(M-Mc) was stabilising around 0.0000014.
I am new to this analysis and I am learning this morning that there's a V2 of this code.
Would you advice me to move to that?

Best regards

**Comment by bvormwald** [comment]
I think it is save to go to 0.000002 for the moment ;-)

As you already mentioned, we are working on a follow-up version of the code. We are just in the final step of cross-checks and will officially release the version soon. The new code is even faster, more flexible with respect to the implementation of other processes and it will solve the energy per fit step exactly in one go (without while-loop). You can of course start to use this version already now (https://github.com/bvormwald/HHKinFit2). Which process are you fitting? H->hh->bbtautau?

**Comment by govoni** [comment]
Hi Benedikt,

yes, that's the process. Thanks a lot for your reply, I'll port the code to the new version then,

Best regards

**Comment by bvormwald** [comment]
Okay, great! But please be aware that there might still come some smaller modifications in the next weeks.

For the heavy Higgs case, you should use the following fitting master class in HHKinFit2: HHKinFitMasterHeavyHiggs.
You should have a look at the arguments of the constructor, but in principle it is working like the former version. We tried to keep the interfaces to the outside world as unchanged as possible. However, please note that you now need to provide the bjet resolution. In the old version this resolution was hard-coded (taken from a the top mass analysis) and we want to disentangle this for the future.

If you find any issue with HHKinFit2, please feel free to open a ticket in this section!
